[phases.setup]
nixPkgs = ['nodejs', 'pnpm']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = [
  'export PUBLIC_BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")',
  'export PUBLIC_VERSION="$(git rev-parse --short HEAD)"',
  'pnpm build'
]

[start]
cmd = 'node build'
