[phases.setup]
nixPkgs = ['nodejs', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile --shamefully-hoist']

[phases.build]
cmds = [
  'export PUBLIC_BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")',
  'pnpm build'
]

[start]
cmd = 'pnpm start'
