[variables]
NODE_VERSION = "24.0.0"

[phases.setup]
nixPkgs = ['nodejs_24', 'pnpm']

[phases.install]
cmds = [
  'pnpm config set engine-strict false',
  'pnpm install --frozen-lockfile --shamefully-hoist'
]

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm start'
