[phases.setup]
nixPkgs = ['nodejs_latest', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile --shamefully-hoist --ignore-engines']

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm start'
