<script lang="ts">
  let { spinner = 1 } = $props();
</script>

{#if spinner == 1}
  <svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
    ><circle cx="4" cy="12" r="0"
      ><animate
        begin="0;spinner_z0Or.end"
        attributeName="r"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="0;3"
        fill="freeze"
      /><animate
        begin="spinner_OLMs.end"
        attributeName="cx"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="4;12"
        fill="freeze"
      /><animate
        begin="spinner_UHR2.end"
        attributeName="cx"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="12;20"
        fill="freeze"
      /><animate
        id="spinner_lo66"
        begin="spinner_Aguh.end"
        attributeName="r"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="3;0"
        fill="freeze"
      /><animate
        id="spinner_z0Or"
        begin="spinner_lo66.end"
        attributeName="cx"
        dur="0.001s"
        values="20;4"
        fill="freeze"
      /></circle
    ><circle cx="4" cy="12" r="3"
      ><animate
        begin="0;spinner_z0Or.end"
        attributeName="cx"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="4;12"
        fill="freeze"
      /><animate
        begin="spinner_OLMs.end"
        attributeName="cx"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="12;20"
        fill="freeze"
      /><animate
        id="spinner_JsnR"
        begin="spinner_UHR2.end"
        attributeName="r"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="3;0"
        fill="freeze"
      /><animate
        id="spinner_Aguh"
        begin="spinner_JsnR.end"
        attributeName="cx"
        dur="0.001s"
        values="20;4"
        fill="freeze"
      /><animate
        begin="spinner_Aguh.end"
        attributeName="r"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="0;3"
        fill="freeze"
      /></circle
    ><circle cx="12" cy="12" r="3"
      ><animate
        begin="0;spinner_z0Or.end"
        attributeName="cx"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="12;20"
        fill="freeze"
      /><animate
        id="spinner_hSjk"
        begin="spinner_OLMs.end"
        attributeName="r"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="3;0"
        fill="freeze"
      /><animate
        id="spinner_UHR2"
        begin="spinner_hSjk.end"
        attributeName="cx"
        dur="0.001s"
        values="20;4"
        fill="freeze"
      /><animate
        begin="spinner_UHR2.end"
        attributeName="r"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="0;3"
        fill="freeze"
      /><animate
        begin="spinner_Aguh.end"
        attributeName="cx"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="4;12"
        fill="freeze"
      /></circle
    ><circle cx="20" cy="12" r="3"
      ><animate
        id="spinner_4v5M"
        begin="0;spinner_z0Or.end"
        attributeName="r"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="3;0"
        fill="freeze"
      /><animate
        id="spinner_OLMs"
        begin="spinner_4v5M.end"
        attributeName="cx"
        dur="0.001s"
        values="20;4"
        fill="freeze"
      /><animate
        begin="spinner_OLMs.end"
        attributeName="r"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="0;3"
        fill="freeze"
      /><animate
        begin="spinner_UHR2.end"
        attributeName="cx"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="4;12"
        fill="freeze"
      /><animate
        begin="spinner_Aguh.end"
        attributeName="cx"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="12;20"
        fill="freeze"
      /></circle
    ></svg
  >
{:else if spinner == 2}
  <svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <path
      d="M12,1A11,11,0,1,0,23,12,11,11,0,0,0,12,1Zm0,19a8,8,0,1,1,8-8A8,8,0,0,1,12,20Z"
      opacity=".25"
    />
    <path
      d="M10.14,1.16a11,11,0,0,0-9,8.92A1.59,1.59,0,0,0,2.46,12,1.52,1.52,0,0,0,4.11,10.7a8,8,0,0,1,6.66-6.61A1.42,1.42,0,0,0,12,2.69h0A1.57,1.57,0,0,0,10.14,1.16Z"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        dur="0.75s"
        values="0 12 12;360 12 12"
        repeatCount="indefinite"
      />
    </path>
  </svg>
{/if}

<style>
  svg {
    fill: currentColor;
  }
</style>
